name: Terraform CI/CD Main

on:
  push:
    branches:
      - main

jobs:
  job-1:
    uses: ./.github/workflows/terraform-validate.yml

  job-2:
    needs: job-1
    uses: ./.github/workflows/terraform-plan.yml

  job-3:
    needs: job-2
    uses: ./.github/workflows/terraform-apply.yml
